(function(){
  const root=document.body.dataset.root||'';
  const getHistory=()=>{try{return JSON.parse(localStorage.getItem('pdfhub-history-tools')||'[]')}catch{return []}};
  const saveHistory=(name,url)=>{const items=getHistory().filter(item=>item.url!==url);items.unshift({name,url});localStorage.setItem('pdfhub-history-tools',JSON.stringify(items.slice(0,12)));};
  const theme=localStorage.getItem('pdfhub-theme')||'dark';
  if(theme==='light')document.body.classList.add('light');
  const menu=document.getElementById('siteMenu');
  const toggle=document.getElementById('menuToggle');
  menu?.querySelector('.menu-theme-row')?.remove();
  if(menu){const home=document.createElement('a');home.className='menu-action';home.href=root+'index.html';home.innerHTML='<i class="fas fa-house"></i><span>Home</span>';menu.querySelector('.menu-list')?.prepend(home);}
  const globalTheme=document.createElement('button');globalTheme.className='global-theme-toggle';globalTheme.type='button';globalTheme.title='Toggle light/dark mode';globalTheme.innerHTML='<span class="t-label" id="themeLabel">Dark</span><span class="toggle-track"><span class="toggle-knob" id="themeKnob"><i class="fas fa-moon"></i></span></span>';globalTheme.onclick=()=>window.toggleTheme();toggle.parentElement.insertBefore(globalTheme,toggle);
  const close=()=>{menu?.classList.remove('open');toggle?.setAttribute('aria-expanded','false');if(toggle)toggle.innerHTML='<i class="fas fa-bars"></i>';};
  toggle?.addEventListener('click',event=>{event.stopPropagation();const open=!menu.classList.contains('open');menu.classList.toggle('open',open);toggle.setAttribute('aria-expanded',String(open));toggle.innerHTML=open?'<i class="fas fa-xmark"></i>':'<i class="fas fa-bars"></i>';});
  document.addEventListener('click',event=>{if(!event.target.closest('#siteMenu')&&!event.target.closest('#menuToggle'))close();});
  document.getElementById('menuSearch')?.addEventListener('submit',event=>{event.preventDefault();location.href=root+'index.html?search='+encodeURIComponent(document.getElementById('menuSearchInput').value);});
  window.toggleTheme=function(){const light=document.body.classList.toggle('light');localStorage.setItem('pdfhub-theme',light?'light':'dark');const label=document.getElementById('themeLabel'),knob=document.getElementById('themeKnob');if(label)label.textContent=light?'Light':'Dark';if(knob)knob.innerHTML=light?'<i class="fas fa-sun"></i>':'<i class="fas fa-moon"></i>';};
  const light=document.body.classList.contains('light');document.getElementById('themeLabel').textContent=light?'Light':'Dark';document.getElementById('themeKnob').innerHTML=light?'<i class="fas fa-sun"></i>':'<i class="fas fa-moon"></i>';
  const count=document.getElementById('dashboardCount');if(count)count.textContent=getHistory().length;
  const notificationCount=document.getElementById('notificationCount');if(notificationCount)notificationCount.textContent=localStorage.getItem('pdfhub-notifications-seen')==='true'?'0':'2';
  const page=document.body.dataset.page;
  const pageMain=document.querySelector('.page-main');
  if(page==='about'){
    pageMain.insertAdjacentHTML('beforeend',`<section class="panel-grid detail-grid" aria-label="About PDFHub details"><article class="panel"><h2>How PDFHub works</h2><p>Choose a tool from the homepage, select a file, configure the available options, and download the result. The interface is designed to keep each workflow focused and easy to review.</p></article><article class="panel"><h2>Privacy-first workflow</h2><p>Most processing happens directly in your browser. PDFHub does not require an account, and your local history and theme preference remain in this browser's storage.</p></article><article class="panel"><h2>Using PDFHub well</h2><p>Keep your original file until you have checked the output. For important documents, compare the generated file with the source and confirm page order, text, signatures, and formatting before sharing.</p></article><article class="panel"><h2>Supported work</h2><p>PDFHub includes tools for organizing, converting, editing, compressing, securing, signing, and extracting information from PDF documents.</p></article><article class="panel"><h2>Local storage controls</h2><p>History and preferences can be cleared through your browser's site-data controls. Clearing that data removes the dashboard activity shown on this device.</p></article><article class="panel"><h2>Contact and feedback</h2><p>For feedback about a tool or the interface, use the creator's linked social channels in the homepage footer. Include the tool name, browser, and a short description of the issue.</p></article></section>`);
  }
  if(page==='terms'){
    pageMain.insertAdjacentHTML('beforeend',`<section class="panel-grid detail-grid" aria-label="Terms and conditions details"><article class="panel"><h2>1. Acceptance</h2><p>By using PDFHub, you agree to these terms. If you do not agree, do not use the service. These terms apply to the website, browser tools, local dashboard, and related pages.</p></article><article class="panel"><h2>2. Permitted use</h2><p>Use PDFHub only for lawful documents and lawful purposes. Do not use it to infringe copyright, evade access controls, distribute malware, violate privacy, or carry out activity prohibited by applicable law.</p></article><article class="panel"><h2>3. Your documents</h2><p>You retain responsibility for the files you select and the rights needed to process them. Keep backups of originals and review every generated file before relying on it.</p></article><article class="panel"><h2>4. Local processing</h2><p>Tools are designed to process files in the browser where supported. Browser storage may retain history and preferences on your device. Do not use a shared device for sensitive work without clearing local data afterward.</p></article><article class="panel"><h2>5. Results and accuracy</h2><p>Conversion, OCR, extraction, and AI-assisted results may contain omissions or formatting differences. PDFHub does not guarantee that an output is complete, accurate, accessible, or suitable for a particular legal, financial, medical, or business purpose.</p></article><article class="panel"><h2>6. Availability and changes</h2><p>Features may change, be interrupted, or be removed as the project evolves. We may update these terms and the tools. Continued use after an update means you accept the revised terms.</p></article><article class="panel"><h2>7. Third-party services</h2><p>Some pages may load fonts, icons, libraries, or other resources from third parties. Their availability and policies are outside PDFHub's control, so review their terms when relevant.</p></article><article class="panel"><h2>8. Disclaimer and liability</h2><p>PDFHub is provided on an as-is and as-available basis. To the extent permitted by law, PDFHub and its creator are not liable for data loss, business interruption, indirect damages, or reliance on generated output.</p></article><article class="panel"><h2>9. Questions</h2><p>Questions about these terms or a tool should include the relevant page, browser, and a reproducible description. Use the creator contact links provided on the homepage.</p></article></section>`);
  }
  if(page==='history'){
    const list=document.getElementById('historyList'),items=getHistory();
    list.innerHTML=items.length?items.map(item=>`<a class="activity-item" href="${root}${item.url}"><i class="fas fa-arrow-up-right-from-square"></i><span>${item.name}</span><small>Recent tool</small></a>`).join(''):'<div class="notice"><i class="fas fa-clock"></i><span>No tool activity yet. Open a PDF tool and it will appear here.</span></div>';
  }
  if(page==='dashboard'){
    const items=getHistory();document.getElementById('toolCount').textContent=items.length;document.getElementById('notificationCountLarge').textContent=localStorage.getItem('pdfhub-notifications-seen')==='true'?'0':'2';
    document.getElementById('dashboardActivity').innerHTML=items.length?items.slice(0,6).map(item=>`<a class="activity-item" href="${root}${item.url}"><i class="fas fa-file-pdf"></i><span>${item.name}</span><small>Available offline</small></a>`).join(''):'<div class="notice"><i class="fas fa-sparkles"></i><span>Your dashboard will populate as you explore PDFHub tools.</span></div>';
    document.getElementById('notificationMessage').textContent=items.length?`Your local workspace has ${items.length} recent tool${items.length===1?'':'s'} ready to revisit.`:'Welcome to PDFHub. Your first tool activity will appear here.';
  }
})();
